# Generated by Django 4.2.7 on 2023-11-14 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('start_datetime', models.DateTimeField(verbose_name='дата и время начала рассылки')),
                ('end_datetime', models.DateTimeField(verbose_name='дата и время окончания рассылки')),
                ('frequency', models.CharField(choices=[('once_day', '1 раз в день'), ('once_week', '1 раз в неделю (по понедельникам)'), ('once_month', '1 раз в месяц (в первый день месяца)')], default='once_day', max_length=20, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('C', 'Создана'), ('R', 'Идет рассылка писем'), ('F', 'Завершена')], default='C', max_length=1, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_message', models.CharField(max_length=50, verbose_name='тема письма')),
                ('body_message', models.TextField(verbose_name='текст письма')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DistributionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='дата и время начала последней рассылки')),
                ('status', models.CharField(choices=[('C', 'Отклонена'), ('F', 'Завершена')], max_length=1, verbose_name='статус')),
                ('server_response', models.CharField(max_length=100, verbose_name='ответ почтового сервера')),
                ('distribution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.distribution', verbose_name='идентификатор рассылки')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='distribution',
            name='message_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribution.message', verbose_name='идентификатор письма для отправки'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='комментарий')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('distribution_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribution.distribution', verbose_name='идентификатор рассылки')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('id',),
            },
        ),
    ]
