# Generated by Django 4.2.7 on 2023-11-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_client_owner_distribution_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'ordering': ('id',), 'permissions': [('set_status', 'Can change_status рассылка')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
