# Generated by Django 4.2.7 on 2023-11-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0010_distributionlogs_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='last_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время окончания рассылки'),
        ),
    ]
